Repository tendermint/flutter, pull requests merged in 2021-11, with the labels that each got.

#110 refactor: Amount formatter
  packages/cosmos_utils/lib/amount_formatter.dart
  packages/cosmos_utils/pubspec.lock
  packages/cosmos_utils/pubspec.yaml
  packages/cosmos_utils/test/number_formatter_test.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#112 feat: onboarding page
  packages/cosmos_ui_components/fonts/inter.ttf
  packages/cosmos_ui_components/lib/components/cosmos_elevated_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_button.dart
  packages/cosmos_ui_components/lib/cosmos_app_theme.dart
  packages/cosmos_ui_components/lib/cosmos_text_theme.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_ui_components/pubspec.yaml
  starport_template/assets/images/welcome-bg.png
  starport_template/ios/Flutter/AppFrameworkInfo.plist
  starport_template/ios/Podfile.lock
  starport_template/lib/main.dart
  starport_template/lib/pages/add_wallet_bottom_sheet.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/import_wallet_page.dart
  starport_template/lib/pages/mnemonic_onboarding_page.dart
  starport_template/lib/pages/onboarding_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/wallets_list_page.dart
  starport_template/lib/starport_app.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#118 feat: add new cosmos_utils extensions
  packages/cosmos_utils/lib/extensions.dart
  packages/cosmos_utils/lib/future_either.dart
Labels: Technical 🛠

#117 style: Update design for balance card in assets portfolio redesign
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_card.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_list_view.dart
Labels: 🎨 Design 🎨

#119 feat: Biometric storage [REVIEW AFTER #118]
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/credentials_storage_failure.dart
  packages/transaction_signing_gateway/lib/storage/biometric_data_store.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/data_store.dart
  packages/transaction_signing_gateway/lib/storage/flutter_secure_storage_data_store.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/shared_prefs_plain_data_store.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/mobile_key_info_storage_test.dart
  packages/transaction_signing_gateway/test/mocks/key_info_storage_mock.dart
  packages/transaction_signing_gateway/test/mocks/test_memory_storage.dart
  packages/transaction_signing_gateway/test/mocks/test_memory_store.dart
  starport_template/pubspec.lock
Labels: Technical 🛠, Feature 💡, 🛠 Refactor 🛠

#122 fix: template compilation errors
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/lib/main.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/pubspec.lock
Labels: Technical 🛠

#121 style: Add `gradient_avatar.dart` along with deterministic color generation from `walletAddress`
  packages/cosmos_ui_components/lib/components/gradient_avatar.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_ui_components/pubspec.yaml
  packages/cosmos_utils/lib/colors_generator.dart
  packages/cosmos_utils/lib/cosmos_utils.dart
Labels: Technical 🛠, 🎨 Design 🎨

#123 fix: Fix dependency reference for cosmos_utils
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_ui_components/pubspec.yaml
Labels: Technical 🛠

#124 feat: Assets portfolio
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_card.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_list_view.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/lib/widgets/asset_portfolio_heading.dart
  starport_template/lib/widgets/balance_card_list.dart
  starport_template/lib/widgets/starport_button_bar.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡, 🎨 Design 🎨

#125 feat: BiometricDataStore improvements
  packages/cosmos_ui_components/assets/images/2.0x/big-arrow-left.png
  packages/cosmos_ui_components/assets/images/3.0x/big-arrow-left.png
  packages/cosmos_ui_components/assets/images/big-arrow-left.png
  packages/cosmos_ui_components/lib/components/cosmos_app_bar.dart
  packages/cosmos_ui_components/lib/components/cosmos_app_bar_action.dart
  packages/cosmos_ui_components/lib/components/cosmos_back_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_button.dart
  packages/cosmos_ui_components/lib/components/info_card.dart
  packages/cosmos_ui_components/lib/cosmos_text_theme.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/lib/fonts/Inter-Black.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-Bold.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-ExtraBold.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-ExtraLight.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-Light.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-Medium.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-Regular.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-SemiBold.ttf
  packages/cosmos_ui_components/lib/fonts/Inter-Thin.ttf
  packages/cosmos_ui_components/lib/fonts/inter.ttf
  packages/cosmos_ui_components/pubspec.yaml
  packages/transaction_signing_gateway/lib/storage/biometric_data_store.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
Labels: Technical 🛠, 🛠 Refactor 🛠

#127 feat: Backup wallet screen - intro
  packages/cosmos_ui_components/pubspec.lock
  starport_template/.idea/runConfigurations.xml
  starport_template/android/app/build.gradle
  starport_template/android/app/src/main/res/values/styles.xml
  starport_template/android/build.gradle
  starport_template/ios/Podfile.lock
  starport_template/ios/Runner.xcodeproj/project.pbxproj
  starport_template/ios/Runner/Info.plist
  starport_template/lib/main.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/onboarding_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/lib/widgets/loading_splash.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: 🎨 Design 🎨

#128 feat: Bottom sheet components
  packages/cosmos_ui_components/assets/images/2.0x/checkbox_checked.png
  packages/cosmos_ui_components/assets/images/2.0x/checkbox_unchecked.png
  packages/cosmos_ui_components/assets/images/3.0x/checkbox_checked.png
  packages/cosmos_ui_components/assets/images/3.0x/checkbox_unchecked.png
  packages/cosmos_ui_components/assets/images/checkbox_checked.png
  packages/cosmos_ui_components/assets/images/checkbox_unchecked.png
  packages/cosmos_ui_components/lib/components/cosmos_app_bar_action.dart
  packages/cosmos_ui_components/lib/components/cosmos_back_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_header.dart
  packages/cosmos_ui_components/lib/components/cosmos_checkbox_tile.dart
  packages/cosmos_ui_components/lib/cosmos_text_theme.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/pubspec.lock
Labels: 🎨 Design 🎨

#129 feat: Backup wallet redesign - Bottom sheet confirmation
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_utils/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/ios/Podfile.lock
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/widgets/backup_later_bottom_sheet.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#130 feat: Account listing bottom sheet
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_header.dart
  packages/cosmos_ui_components/lib/components/cosmos_circle_text_button.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_wallet_list_item.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_wallets_list_view.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/wallets_list_page.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/lib/widgets/asset_portfolio_heading.dart
  starport_template/lib/widgets/backup_later_bottom_sheet.dart
  starport_template/lib/widgets/wallets_list_sheet.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡, 🎨 Design 🎨

#132 fix: Fix dependency in pubspec.yaml
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: bug 🐛, Technical 🛠

#133 feat: Open wallet after successful wallet creation
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/lib/widgets/loading_splash.dart
Labels: Feature 💡

#131 feat: Add cosmos_adaptive_action_sheet.dart
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_action_sheet.dart
  packages/cosmos_ui_components/lib/cosmos_text_theme.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
Labels: 🎨 Design 🎨

#134 feat: Back up wallet page - components
  packages/cosmos_ui_components/lib/components/cosmos_app_bar_action.dart
  packages/cosmos_ui_components/lib/components/cosmos_back_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_button.dart
  packages/cosmos_ui_components/lib/components/info_card.dart
  packages/cosmos_ui_components/lib/components/mnemonic_choice_chip.dart
  packages/cosmos_ui_components/lib/components/mnemonic_words_grid.dart
  packages/cosmos_ui_components/lib/cosmos_text_theme.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_utils/lib/mnemonic.dart
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/pubspec.lock
Labels: 🎨 Design 🎨

#136 fix: Bottom sheet header fix
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_header.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
Labels: bug 🐛, 🎨 Design 🎨

#135 feat: Back up wallet page
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/assets/images/2.0x/icon_check_16.png
  starport_template/assets/images/2.0x/icon_copy_16.png
  starport_template/assets/images/3.0x/icon_check_16.png
  starport_template/assets/images/3.0x/icon_copy_16.png
  starport_template/assets/images/icon_check_16.png
  starport_template/assets/images/icon_copy_16.png
  starport_template/lib/pages/back_up_wallet_page.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/widgets/copy_to_clipboard_button.dart
  starport_template/lib/widgets/loading_splash.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#138 feat: Add function for updating public wallet info using plain data store
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#139 feat: Repeat mnemonic page - components
  packages/cosmos_ui_components/lib/components/cosmos_back_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_ui_components/lib/components/cosmos_mnemonic_confirm_view.dart
  packages/cosmos_ui_components/lib/components/mnemonic_choice_chip.dart
  packages/cosmos_ui_components/lib/components/mnemonic_words_grid.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_heading.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_ui_components/pubspec.yaml
Labels: 🎨 Design 🎨

#140 feat: Repeat mnemonic page
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/lib/pages/back_up_wallet_page.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/repeat_mnemonic_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/pubspec.lock
Labels: Feature 💡
