Repository tendermint/flutter, pull requests merged in 2021-07, with the labels that each got.

#62 feat: key info storage implementation
  packages/transaction_signing_gateway/lib/encrypt/aes_cipher.dart
  packages/transaction_signing_gateway/lib/encrypt/cipher.dart
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/key_info_storage.dart
  packages/transaction_signing_gateway/lib/mobile/mobile_key_info_storage.dart
  packages/transaction_signing_gateway/lib/model/credentials_storage_failure.dart
  packages/transaction_signing_gateway/lib/model/private_wallet_credentials.dart
  packages/transaction_signing_gateway/lib/model/private_wallet_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/model/transaction_signing_failure.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/utils/future_either.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/aes_cipher_test.dart
  packages/transaction_signing_gateway/test/mobile_key_info_storage_test.dart
  packages/transaction_signing_gateway/test/mocks/key_info_storage_mock.dart
  packages/transaction_signing_gateway/test/mocks/private_wallet_credentials_mock.dart
  packages/transaction_signing_gateway/test/mocks/test_memory_storage.dart
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
Labels: Technical 🛠

#63 feat: Wallets List + password verify
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/key_info_storage.dart
  packages/transaction_signing_gateway/lib/mobile/mobile_key_info_storage.dart
  packages/transaction_signing_gateway/lib/model/private_wallet_credentials.dart
  packages/transaction_signing_gateway/lib/model/wallet_lookup_key.dart
  packages/transaction_signing_gateway/lib/model/wallet_public_info.dart
  packages/transaction_signing_gateway/lib/model/wallet_public_info_serializer.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/test/mobile_key_info_storage_test.dart
  packages/transaction_signing_gateway/test/mocks/key_info_storage_mock.dart
  packages/transaction_signing_gateway/test/mocks/private_wallet_credentials_mock.dart
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
Labels: Feature 💡, Technical 🛠

#64 feat: [transaction_signing_gateway] add documentation + example implementat…
  packages/transaction_signing_gateway/README.md
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/mobile/no_op_transaction_summary_ui.dart
  packages/transaction_signing_gateway/lib/model/wallet_public_info.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_private_wallet_credentials.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_transaction.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_transaction_signer.dart
  packages/transaction_signing_gateway/lib/transaction_signer.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/transaction_summary_ui.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/sacco_credentials_serializer_test.dart
Labels: Feature 💡, Technical 🛠

#66 feat: Transition from sacco to alan library for transaction signing
  packages/transaction_signing_gateway/lib/alan/alan_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/alan/alan_private_wallet_credentials.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction_signer.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_transaction.dart
  packages/transaction_signing_gateway/lib/sacco/sacco_transaction_signer.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/alan_credentials_serializer_test.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#67 feat: Alan transaction signing improvements
  packages/transaction_signing_gateway/lib/alan/alan_transaction.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction_signer.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
Labels: Technical 🛠
