Repository tendermint/flutter, pull requests merged in 2021-06, with the labels that each got.

#18 documentation: Update README.md
  README.md
Labels: documentation

#37 feat: Set up FVM + clean up flutter-generated files
  .gitignore
  .idea/.gitignore
  .idea/vcs.xml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  macos/.gitignore
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Runner.xcworkspace/contents.xcworkspacedata
  macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  macos/Runner/AppDelegate.swift
  macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  macos/Runner/Base.lproj/MainMenu.xib
  macos/Runner/Configs/AppInfo.xcconfig
  macos/Runner/Configs/Debug.xcconfig
  macos/Runner/Configs/Release.xcconfig
  macos/Runner/Configs/Warnings.xcconfig
  macos/Runner/DebugProfile.entitlements
  macos/Runner/Info.plist
  macos/Runner/MainFlutterWindow.swift
  macos/Runner/Release.entitlements
  pubspec.lock
Labels: Technical 🛠

#38 feat: set up dart analysis + fix lint errors
  analysis_options.yaml
  lib/api_calls/faucet_api.dart
  lib/api_calls/wallet_api.dart
  lib/global.dart
  lib/helpers/mnemonic_encryptor.dart
  lib/helpers/mnemonic_generator.dart
  lib/main.dart
  lib/models/balances.dart
  lib/models/transaction.dart
  lib/views/mnemonic_onboarding.dart
  lib/views/password_generation.dart
  lib/views/wallet_details_page.dart
  lib/views/wallet_list.dart
  pubspec.lock
  pubspec.yaml
  test/ethereum_test.dart
  test/transaction _test_hosted.dart
  test/transaction _test_local.dart
  test/transaction_test_hosted.dart
  test/transaction_test_local.dart
Labels: Technical 🛠

#39 feat: CI Setup
  .github/workflows/deploy.yml
  .github/workflows/pull-request.yml
  lib/views/mnemonic_onboarding.dart
  test/widget_test.dart
Labels: Technical 🛠

#43 feat: Add UI support for Ethereum
  README.md
  lib/api_calls/base_wallet_api.dart
  lib/api_calls/cosmos_api.dart
  lib/api_calls/ethereum_api.dart
  lib/global.dart
  lib/main.dart
  lib/models/balances.dart
  lib/models/cosmos_wallet.dart
  lib/models/emeris_wallet.dart
  lib/models/ethereum_wallet.dart
  lib/models/wallet_details.dart
  lib/models/wallet_type.dart
  lib/views/password_generation.dart
  lib/views/wallet_details_page.dart
  lib/views/wallet_list.dart
  test/ethereum_test.dart
  test/transaction_hosted_test.dart
  test/transaction_local_test.dart
  test/transaction_test_local.dart
Labels: Feature 💡

#46 feat: Add Intellij's File templates
  .idea/file.template.settings.xml
  .idea/fileTemplates/mobxPage.dart
  .idea/fileTemplates/mobxPage.dart.child.0.dart
  .idea/fileTemplates/mobxPage.dart.child.1.dart
  .idea/fileTemplates/mobxPage.dart.child.2.dart
  .idea/fileTemplates/mobxPage.dart.child.3.dart
  .idea/fileTemplates/useCase.dart
  .idea/fileTemplates/useCase.dart.child.0.dart
Labels: Technical 🛠

#47 feat: Restructure packages
  lib/app_widget.dart
  lib/data/api_calls/base_wallet_api.dart
  lib/data/api_calls/cosmos_api.dart
  lib/data/api_calls/ethereum_api.dart
  lib/data/api_calls/faucet_api.dart
  lib/data/model/balances.dart
  lib/data/model/cosmos_wallet.dart
  lib/data/model/emeris_wallet.dart
  lib/data/model/ethereum_wallet.dart
  lib/data/model/transaction.dart
  lib/data/model/wallet_type.dart
  lib/dependency_injection/app_component.dart
  lib/global.dart
  lib/main.dart
  lib/views/wallet_details_page.dart
  lib/views/wallet_list.dart
  pubspec.lock
  pubspec.yaml
  test/transaction_hosted_test.dart
  test/transaction_local_test.dart
Labels: Technical 🛠

#49 feat: Analysis improvements + App navigator
  analysis_options.yaml
  lib/app_widget.dart
  lib/domain/model/failures/displayable_failure.dart
  lib/helpers/mnemonic_encryptor.dart
  lib/navigation/app_navigator.dart
  lib/navigation/error_dialog_route.dart
  lib/navigation/no_routes.dart
  lib/utils/app_theme.dart
  lib/utils/durations.dart
  lib/utils/logger.dart
  lib/utils/utils.dart
  lib/views/wallet_list.dart
  pubspec.lock
  pubspec.yaml
Labels: Technical 🛠

#50 feat: Refactor wallets list to new architecture
  lib/dependency_injection/app_component.dart
  lib/domain/entities/import_wallet_form_data.dart
  lib/domain/model/failures/add_wallet_failure.dart
  lib/domain/use_cases/import_wallet_use_case.dart
  lib/presentation/wallets_list/wallets_list_initial_params.dart
  lib/presentation/wallets_list/wallets_list_presentation_model.dart
  lib/presentation/wallets_list/wallets_list_presenter.dart
  lib/ui/pages/add_wallet/add_wallet_bottom_sheet.dart
  lib/ui/pages/wallets_list/wallets_list_navigator.dart
  lib/ui/pages/wallets_list/wallets_list_page.dart
  lib/ui/pages/wallets_list/widgets/wallets_list_view.dart
  lib/ui/widgets/content_empty_loading_switcher.dart
  lib/ui/widgets/content_loading_indicator.dart
  lib/ui/widgets/emeris_app_bar.dart
  lib/ui/widgets/empty_list_message.dart
  lib/views/password_generation.dart
  lib/views/wallet_details_page.dart
  lib/views/wallet_list.dart
Labels: 🛠 Refactor 🛠

#53 feat: Localization support
  l10n.yaml
  lib/app_widget.dart
  lib/l10n/app_en.arb
  lib/utils/strings.dart
  lib/views/mnemonic_onboarding.dart
  lib/views/password_generation.dart
  pubspec.yaml
Labels: Technical 🛠

#58 feat: Localisation of hardcoded strings
  lib/l10n/app_en.arb
  lib/ui/pages/add_wallet/add_wallet_bottom_sheet.dart
  lib/ui/pages/wallets_list/wallets_list_page.dart
  lib/views/mnemonic_onboarding.dart
  lib/views/password_generation.dart
  lib/views/wallet_details_page.dart
Labels: Technical 🛠, 🛠 Refactor 🛠
