Repository tendermint/flutter, pull requests merged in 2021-08, with the labels that each got.

#70 feat: add static analysis to packages
  packages/cosmos_ui_components/analysis_options.yaml
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_ui_components/pubspec.yaml
  starport_template/analysis_options.yaml
  starport_template/lib/main.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Technical 🛠

#72 feat: Transaction broadcasting
  packages/transaction_signing_gateway/lib/alan/alan_transaction_broadcaster.dart
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/transaction_broadcasting_failure.dart
  packages/transaction_signing_gateway/lib/model/transaction_hash.dart
  packages/transaction_signing_gateway/lib/transaction_broadcaster.dart
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
Labels: Feature 💡, Technical 🛠

#73 feat: Template - routing page
  packages/cosmos_ui_components/lib/components/content_state_switcher.dart
  packages/cosmos_ui_components/lib/components/cosmos_error_view.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/pubspec.yaml
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/lib/main.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/wallets_list_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#74 feat: export starport tpl as a Go module
  flutter.go
  go.mod
Labels: Feature 💡

#75 feat: new UI components - wallets list
  packages/cosmos_ui_components/lib/components/empty_list_message.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_wallet_list_item.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_wallets_list_view.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
Labels: Feature 💡

#76 feat: template - wallets list page
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  starport_template/lib/pages/add_wallet_page.dart
  starport_template/lib/pages/mnemonic_onboarding_page.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/lib/pages/wallets_list_page.dart
  starport_template/lib/widgets/password_setup_sheet.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#77 feat: Add cosmos_password_field.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_password_field.dart
Labels: 🛠 Refactor 🛠

#81 feat: Add components for wallet details page
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_card.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_heading.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_list_view.dart
  packages/cosmos_ui_components/lib/cosmos_app_theme.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#83 refactor: Update branch reference for `cosmos_ui_components`
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Technical 🛠, 🛠 Refactor 🛠

#84 feat: Support dark and light theme in ui components
  packages/cosmos_ui_components/lib/cosmos_app_theme.dart
  starport_template/pubspec.yaml
Labels: 🎨 Design 🎨

#85 refactor: Add version for `alan` in pubspec.yaml
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Technical 🛠, 🛠 Refactor 🛠

#89 fix: MobX mutation actions
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/lib/stores/wallets_store.dart
Labels: Technical 🛠

#88 refactor: Wallet derivation
  packages/transaction_signing_gateway/lib/alan/alan_wallet_derivation_info.dart
  packages/transaction_signing_gateway/lib/alan/alan_wallet_derivator.dart
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/wallet_derivation_failure.dart
  packages/transaction_signing_gateway/lib/model/wallet_derivation_info.dart
  packages/transaction_signing_gateway/lib/wallet_derivator.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#90 feat: Add default parameters to TransactionSigningGateway constructor + update dependencies
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_utils/pubspec.lock
  packages/cosmos_utils/pubspec.yaml
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  starport_template/android/app/build.gradle
Labels: Technical 🛠

#91 feat: Template Tweaks
  .github/workflows/pull-request.yml
  .github/workflows/semantic-pull-request.yml
  starport_template/lib/pages/mnemonic_onboarding_page.dart
  starport_template/lib/pages/wallets_list_page.dart
Labels: 🎨 Design 🎨

#94 fix: Starport Template pre-release fixes
  starport_template/lib/entities/import_wallet_form_data.dart
  starport_template/lib/main.dart
  starport_template/lib/pages/add_wallet_bottom_sheet.dart
  starport_template/lib/pages/add_wallet_page.dart
  starport_template/lib/pages/mnemonic_onboarding_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/lib/pages/wallets_list_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/lib/utils/base_env.dart
  starport_template/lib/utils/cosmos_balances.dart
  starport_template/lib/utils/token_sender.dart
  starport_template/lib/widgets/password_setup_sheet.dart
  starport_template/lib/widgets/send_money_sheet.dart
  starport_template/pubspec.lock
Labels: bug 🐛, 🛠 Refactor 🛠
