Repository tendermint/flutter, pull requests merged in 2022-02, with the labels that each got.

#204 fix: Fix cosmos_outline_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_elevated_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_outline_button.dart
  packages/cosmos_ui_components/lib/utils/global_constants.dart
Labels: bug 🐛, 🎨 Design 🎨

#206 feat: update starport_template with newest packages' code
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/ios/Podfile.lock
  starport_template/lib/pages/receive_money_sheet.dart
  starport_template/pubspec.lock
Labels: 🚧 WORK IN PROGRESS 🚧, 🔴 DO NOT MERGE 🔴, 🛠 Refactor 🛠

#216 fix: fixed address button style
  starport_template/lib/pages/receive_money_sheet.dart
  starport_template/pubspec.lock
Labels: bug 🐛

#217 fix: (balance) :bug: fixed multiple balance load bug
  Makefile
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/import_wallet_page.dart
  starport_template/lib/pages/sign_transaction_page.dart
Labels: bug 🐛

#220 fix: (android) 🐛 bump up android and kotlin versions
  starport_template/android/app/build.gradle
  starport_template/android/build.gradle
Labels: bug 🐛

#221 feat: make firstOrNull's predicate optional
  packages/cosmos_utils/lib/extensions.dart
  starport_template/lib/stores/wallets_store.dart
Labels: Technical 🛠, Feature 💡

#222 fix: HTTPS communication with testnet
  starport_template/lib/utils/base_env.dart
Labels: bug 🐛
