Repository tendermint/flutter, pull requests merged in 2022-05, with the labels that each got.

#268 refactor: Add theme support for `CosmosElevatedButton` and `CosmosOutlinedButton`
  packages/cosmos_ui_components/lib/components/cosmos_elevated_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_outline_button.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#269 refactor: Add `CosmosTheme` support for more components
  packages/cosmos_ui_components/lib/components/app_version_text.dart
  packages/cosmos_ui_components/lib/components/chip_text.dart
  packages/cosmos_ui_components/lib/components/content_loading_indicator.dart
  packages/cosmos_ui_components/lib/components/cosmos_app_bar.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_button.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#271 refactor: Add more components to support `CosmosTheme`
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_header.dart
  packages/cosmos_ui_components/lib/components/cosmos_checkbox_tile.dart
  packages/cosmos_ui_components/lib/components/cosmos_circle_text_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_button.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#274 refactor: Update theme support for `CosmosTextField`
  packages/cosmos_ui_components/lib/components/cosmos_text_field.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#273 fix: Fix `CosmosCheckboxTile` for dark/light themes
  packages/cosmos_ui_components/assets/images/2.0x/checkbox_checked.png
  packages/cosmos_ui_components/assets/images/3.0x/checkbox_checked.png
  packages/cosmos_ui_components/assets/images/checkbox_checked.png
  packages/cosmos_ui_components/lib/components/cosmos_checkbox_tile.dart
Labels: bug 🐛, 🎨 Design 🎨

#275 refactor: Add `CosmosTheme` support for `CosmosPasscodePrompt`
  packages/cosmos_ui_components/lib/components/cosmos_passcode_prompt.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#277 refactor: Theme support for different components
  packages/cosmos_ui_components/assets/images/2.0x/receive_icon.png
  packages/cosmos_ui_components/assets/images/3.0x/receive_icon.png
  packages/cosmos_ui_components/assets/images/receive_icon.png
  packages/cosmos_ui_components/lib/components/cosmos_warning_box.dart
  packages/cosmos_ui_components/lib/components/empty_list_message.dart
  packages/cosmos_ui_components/lib/components/info_card.dart
  packages/cosmos_ui_components/lib/components/mnemonic_choice_chip.dart
  packages/cosmos_ui_components/lib/components/mnemonic_words_grid.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_account_list_item.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_balance_card.dart
  packages/cosmos_ui_components/lib/components/template/settings_item.dart
  packages/cosmos_ui_components/lib/components/template/transaction_history_card.dart
  packages/cosmos_ui_components/lib/components/template/transaction_history_group_title.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#276 refactor: Update custom switch to have Cosmos specific gradient
  packages/cosmos_ui_components/assets/images/2.0x/toggle.png
  packages/cosmos_ui_components/assets/images/3.0x/toggle.png
  packages/cosmos_ui_components/assets/images/toggle.png
  packages/cosmos_ui_components/lib/components/cosmos_qr_image.dart
  packages/cosmos_ui_components/lib/components/cosmos_switch.dart
  packages/cosmos_ui_components/lib/utils/global_constants.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#279 fix: Fix disabled style for `CosmosElevatedButton`
  packages/cosmos_ui_components/lib/components/cosmos_elevated_button.dart
Labels: bug 🐛, 🎨 Design 🎨

#280 fix: Fix background color for `CosmosBottomSheetContainer` and border color for `CosmosMnemonicConfirmView`
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_ui_components/lib/components/cosmos_mnemonic_confirm_view.dart
Labels: bug 🐛, 🎨 Design 🎨

#290 refactor: Update `CosmosTheme` to support brightness and dark/light theme as constructor parameters
  packages/cosmos_ui_components/lib/cosmos_theme.dart
  packages/cosmos_ui_components/lib/utils/theme_converter.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#281 feat: Dark theme
  starport_template/lib/main.dart
  starport_template/lib/pages/account_name_page.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/assets_transfer_sheet.dart
  starport_template/lib/pages/back_up_account_page.dart
  starport_template/lib/pages/create_account_page.dart
  starport_template/lib/pages/custom_fee_page.dart
  starport_template/lib/pages/import_account_page.dart
  starport_template/lib/pages/passcode_prompt_page.dart
  starport_template/lib/pages/receive_money_sheet.dart
  starport_template/lib/pages/repeat_mnemonic_page.dart
  starport_template/lib/pages/security_sheet.dart
  starport_template/lib/pages/select_asset_page.dart
  starport_template/lib/pages/settings_sheet.dart
  starport_template/lib/pages/sign_transaction_page.dart
  starport_template/lib/pages/transaction_history_page.dart
  starport_template/lib/pages/transfer_asset_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/theme_store.dart
  starport_template/lib/widgets/asset_portfolio_heading.dart
  starport_template/lib/widgets/sign_transaction_tab_view_item.dart
  starport_template/pubspec.lock
Labels: Feature 💡

#292 fix: CosmosTheme inherited widgets updates
  packages/cosmos_ui_components/lib/cosmos_theme.dart
Labels: bug 🐛

#293 fix: Remove input decoration theme from theme_converter.dart
  packages/cosmos_ui_components/lib/utils/theme_converter.dart
Labels: bug 🐛, 🎨 Design 🎨

#296 refactor: Introduce optional colors for `CosmosOutlineButton`
  packages/cosmos_ui_components/lib/components/cosmos_outline_button.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨
