Repository tendermint/flutter, pull requests merged in 2022-03, with the labels that each got.

#219 fix: (transaction) 🐛 fixed amount denom
  Makefile
  starport_template/lib/entities/amount.dart
  starport_template/lib/entities/balance.dart
  starport_template/lib/pages/assets_transfer_sheet.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/sign_transaction_page.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/lib/utils/token_sender.dart
Labels: bug 🐛

#226 refactor: Rename wallet to account
  packages/transaction_signing_gateway/CHANGELOG.md
  packages/transaction_signing_gateway/lib/account_derivator.dart
  packages/transaction_signing_gateway/lib/alan/alan_account_derivation_info.dart
  packages/transaction_signing_gateway/lib/alan/alan_account_derivator.dart
  packages/transaction_signing_gateway/lib/alan/alan_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/alan/alan_private_account_credentials.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction_broadcaster.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction_signer.dart
  packages/transaction_signing_gateway/lib/alan/alan_wallet_derivation_info.dart
  packages/transaction_signing_gateway/lib/alan/alan_wallet_derivator.dart
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/account_derivation_failure.dart
  packages/transaction_signing_gateway/lib/model/account_derivation_info.dart
  packages/transaction_signing_gateway/lib/model/account_lookup_key.dart
  packages/transaction_signing_gateway/lib/model/account_public_info.dart
  packages/transaction_signing_gateway/lib/model/account_public_info_serializer.dart
  packages/transaction_signing_gateway/lib/model/private_account_credentials.dart
  packages/transaction_signing_gateway/lib/model/private_account_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/model/private_wallet_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/model/transaction_broadcasting_failure.dart
  packages/transaction_signing_gateway/lib/model/transaction_signing_failure.dart
  packages/transaction_signing_gateway/lib/model/wallet_derivation_failure.dart
  packages/transaction_signing_gateway/lib/model/wallet_derivation_info.dart
  packages/transaction_signing_gateway/lib/storage/biometric_data_store.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
  packages/transaction_signing_gateway/lib/transaction_broadcaster.dart
  packages/transaction_signing_gateway/lib/transaction_signer.dart
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/wallet_derivator.dart
  packages/transaction_signing_gateway/test/account_public_info_serializer_test.dart
  packages/transaction_signing_gateway/test/alan_credentials_serializer_test.dart
  packages/transaction_signing_gateway/test/mobile_key_info_storage_test.dart
  packages/transaction_signing_gateway/test/mocks/key_info_storage_mock.dart
  packages/transaction_signing_gateway/test/mocks/private_account_credentials_mock.dart
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
  packages/transaction_signing_gateway/test/wallet_public_info_serializer_test.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#227 refactor: Refactor wallet entities in `cosmos_ui_components`
  packages/cosmos_ui_components/CHANGELOG.md
  packages/cosmos_ui_components/lib/components/template/cosmos_account_list_item.dart
  packages/cosmos_ui_components/lib/components/template/cosmos_accounts_list_view.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/lib/models/account_info.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#228 refactor: Rename the wallet to account for `cosmos_auth`
  packages/cosmos_auth/lib/auth/cosmos_auth.dart
  packages/cosmos_auth/lib/biometrics/biometrics.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#229 refactor: Rename everything from wallet to account in `starport_template`
  starport_template/lib/entities/account_additional_data.dart
  starport_template/lib/entities/import_account_form_data.dart
  starport_template/lib/main.dart
  starport_template/lib/pages/account_name_page.dart
  starport_template/lib/pages/accounts_list_sheet.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/assets_transfer_sheet.dart
  starport_template/lib/pages/back_up_account_page.dart
  starport_template/lib/pages/create_account_page.dart
  starport_template/lib/pages/custom_fee_page.dart
  starport_template/lib/pages/import_account_page.dart
  starport_template/lib/pages/onboarding_page.dart
  starport_template/lib/pages/passcode_prompt_page.dart
  starport_template/lib/pages/receive_money_sheet.dart
  starport_template/lib/pages/repeat_mnemonic_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/send_money_sheet.dart
  starport_template/lib/pages/sign_transaction_page.dart
  starport_template/lib/pages/transaction_history_page.dart
  starport_template/lib/pages/transfer_asset_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/accounts_store.dart
  starport_template/lib/stores/transactions_store.dart
  starport_template/lib/utils/cosmos_balances.dart
  starport_template/lib/utils/cosmos_transaction_history_loader.dart
  starport_template/lib/utils/token_sender.dart
  starport_template/lib/widgets/send_money_form.dart
  starport_template/pubspec.lock
Labels: Technical 🛠, 🛠 Refactor 🛠

#233 feat: ExpandableContainer widget
  packages/cosmos_ui_components/lib/components/expandable_container.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_utils/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/pubspec.lock
Labels: Feature 💡

#234 feat: improve error logging for catched errors
  packages/transaction_signing_gateway/lib/alan/alan_account_derivator.dart
  packages/transaction_signing_gateway/lib/alan/alan_credentials_serializer.dart
  packages/transaction_signing_gateway/lib/alan/alan_transaction_signer.dart
  packages/transaction_signing_gateway/lib/model/account_derivation_failure.dart
  packages/transaction_signing_gateway/lib/storage/biometric_data_store.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/flutter_secure_storage_data_store.dart
  packages/transaction_signing_gateway/lib/storage/shared_prefs_plain_data_store.dart
Labels: Feature 💡

#231 refactor: return TransactionResponse instead of TransactionHash after successful broadcast
  packages/transaction_signing_gateway/lib/alan/alan_transaction_broadcaster.dart
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/transaction_hash.dart
  packages/transaction_signing_gateway/lib/model/transaction_log.dart
  packages/transaction_signing_gateway/lib/model/transaction_response.dart
  packages/transaction_signing_gateway/lib/transaction_broadcaster.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  starport_template/lib/utils/token_sender.dart
Labels: 🛠 Refactor 🛠

#239 feat: minor theme updates
  packages/cosmos_ui_components/lib/components/cosmos_elevated_button.dart
  packages/cosmos_ui_components/lib/components/cosmos_text_field.dart
  packages/cosmos_ui_components/lib/cosmos_theme.dart
Labels: Feature 💡, 🎨 Design 🎨

#237 feat: clear local storage
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
  packages/transaction_signing_gateway/test/mocks/test_memory_store.dart
Labels: Feature 💡

#243 feat: add "clearCredentials" function to transaction_signing_gateway
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/model/clear_credentials_failure.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
Labels: Feature 💡
