Repository tendermint/flutter, pull requests merged in 2022-01, with the labels that each got.

#180 fix: Add missing image `arrow_right.png` for settings item
  packages/cosmos_ui_components/assets/images/2.0x/arrow_right.png
  packages/cosmos_ui_components/assets/images/3.0x/arrow_right.png
  packages/cosmos_ui_components/assets/images/arrow_right.png
Labels: bug 🐛

#181 refactor: Add app_info_provider.dart
  packages/cosmos_utils/lib/app_info_provider.dart
  packages/cosmos_utils/lib/cosmos_utils.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#182 fix: storing data otside of SharedPrefsPlainDataStore
  packages/transaction_signing_gateway/lib/storage/shared_prefs_plain_data_store.dart
  packages/transaction_signing_gateway/test/mocks/stub_shared_preferences.dart
  packages/transaction_signing_gateway/test/shared_prefs_plain_data_store_test.dart
  starport_template/.idea/runConfigurations.xml
Labels: bug 🐛

#183 fix: Update dependency refs
  packages/cosmos_ui_components/pubspec.lock
  packages/cosmos_utils/pubspec.lock
  packages/transaction_signing_gateway/lib/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Technical 🛠

#184 feat: cosmos_auth package
  .github/workflows/pull-request.yml
  packages/cosmos_auth/.gitignore
  packages/cosmos_auth/CHANGELOG.md
  packages/cosmos_auth/LICENSE
  packages/cosmos_auth/README.md
  packages/cosmos_auth/analysis_options.yaml
  packages/cosmos_auth/lib/auth/cosmos_auth.dart
  packages/cosmos_auth/lib/auth/model/local_auth_failure.dart
  packages/cosmos_auth/lib/cosmos_auth.dart
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_auth/pubspec.yaml
  packages/cosmos_auth/test/sample_test.dart
Labels: Feature 💡

#187 fix: Remove throw from getter in transaction_signing_failure.dart
  packages/transaction_signing_gateway/lib/model/transaction_signing_failure.dart
Labels: bug 🐛

#188 feat: add delete wallet to transaction_signing_gateway
  packages/transaction_signing_gateway/lib/gateway/transaction_signing_gateway.dart
  packages/transaction_signing_gateway/lib/storage/cosmos_key_info_storage.dart
  packages/transaction_signing_gateway/lib/storage/key_info_storage.dart
Labels: Feature 💡, Requires Review 👀

#185 refactor: migrate to cosmos_auth package
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/lib/storage/biometric_data_store.dart
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/utils/user_authenticator.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡, 🛠 Refactor 🛠

#189 feat: Starport Template - Android Deployment
  .github/workflows/deploy-firebase-android.yml
  .github/workflows/deploy-firebase-ios.yml
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/android/Gemfile
  starport_template/android/Gemfile.lock
  starport_template/android/app/build.gradle
  starport_template/android/app/src/debug/AndroidManifest.xml
  starport_template/android/app/src/main/kotlin/com/starport/template/MainActivity.kt
  starport_template/android/app/src/profile/AndroidManifest.xml
  starport_template/android/fastlane/Appfile
  starport_template/android/fastlane/Fastfile
  starport_template/android/fastlane/Pluginfile
  starport_template/android/fastlane/README.md
  starport_template/build/ios/Runner.build/Release-iphoneos/Runner.build/dgph
  starport_template/pubspec.lock
Labels: Technical 🛠, Feature 💡

#190 refactor: Make title as nullable property and adjust height based on empty title
  packages/cosmos_ui_components/lib/components/cosmos_app_bar.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#191 refactor: biometrics refactor - part 1 - cosmos_utils
  packages/cosmos_utils/lib/cosmos_utils.dart
  packages/cosmos_utils/lib/credentials_storage_failure.dart
  packages/cosmos_utils/lib/data_store.dart
Labels: 🛠 Refactor 🛠

#192 refactor: biometrics refactor - part 2 - cosmos_auth
  packages/cosmos_auth/lib/auth/cosmos_auth.dart
  packages/cosmos_auth/lib/biometrics/biometrics.dart
  packages/cosmos_auth/lib/cosmos_auth.dart
  packages/cosmos_auth/lib/model/local_auth_failure.dart
  packages/cosmos_auth/lib/model/read_password_failure.dart
  packages/cosmos_auth/lib/model/save_password_failure.dart
  packages/cosmos_auth/lib/store/password_store.dart
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_auth/pubspec.yaml
  packages/cosmos_auth/test/cosmos_auth_test.dart
  packages/cosmos_auth/test/mocks/mocks.dart
  packages/cosmos_auth/test/sample_test.dart
  packages/cosmos_ui_components/.idea/runConfigurations.xml
  packages/cosmos_ui_components/pubspec.lock
Labels: 🛠 Refactor 🛠

#194 refactor: biometrics refactor - part 4 - starport_template
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/ios/Podfile
  starport_template/ios/Podfile.lock
  starport_template/ios/Runner.xcodeproj/project.pbxproj
  starport_template/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  starport_template/lib/main.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/import_wallet_page.dart
  starport_template/lib/pages/passcode_prompt_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/wallets_store.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: 🛠 Refactor 🛠

#196 feat: add getAvailableBiometrics & CosmosSwitch
  packages/cosmos_auth/lib/auth/cosmos_auth.dart
  packages/cosmos_auth/lib/biometrics/biometrics.dart
  packages/cosmos_auth/lib/cosmos_auth.dart
  packages/cosmos_auth/lib/model/biometric_type.dart
  packages/cosmos_auth/lib/model/local_auth_failure.dart
  packages/cosmos_ui_components/lib/components/cosmos_switch.dart
  packages/cosmos_ui_components/lib/components/template/settings_item.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
Labels: Feature 💡

#197 feat: settings screen
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/lib/main.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/assets_transfer_sheet.dart
  starport_template/lib/pages/backup_later_bottom_sheet.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/passcode_prompt_page.dart
  starport_template/lib/pages/routing_page.dart
  starport_template/lib/pages/security_sheet.dart
  starport_template/lib/pages/send_money_sheet.dart
  starport_template/lib/pages/settings_sheet.dart
  starport_template/lib/pages/sign_transaction_page.dart
  starport_template/lib/pages/transaction_history_page.dart
  starport_template/lib/pages/wallets_list_sheet.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/settings_store.dart
  starport_template/lib/widgets/settings_sheet.dart
  starport_template/pubspec.lock
  starport_template/pubspec.yaml
Labels: Feature 💡

#198 feat: Starport template - quality improvements
  packages/cosmos_ui_components/lib/components/cosmos_bottom_sheet_container.dart
  packages/cosmos_utils/lib/extensions.dart
  starport_template/README.md
  starport_template/android/app/src/debug/AndroidManifest.xml
  starport_template/android/app/src/main/AndroidManifest.xml
  starport_template/android/app/src/profile/AndroidManifest.xml
  starport_template/lib/main.dart
  starport_template/lib/pages/assets_portfolio_page.dart
  starport_template/lib/pages/create_wallet_page.dart
  starport_template/lib/pages/onboarding_page.dart
  starport_template/lib/pages/passcode_prompt_page.dart
  starport_template/lib/pages/password_setup_sheet.dart
  starport_template/lib/pages/receive_money_sheet.dart
  starport_template/lib/pages/security_sheet.dart
  starport_template/lib/pages/transaction_history_page.dart
  starport_template/lib/pages/wallet_details_page.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/settings_store.dart
  starport_template/lib/widgets/balance_card_list.dart
  starport_template/lib/widgets/receive_money_sheet.dart
Labels: Technical 🛠

#199 docs: Update readme
  starport_template/README.md
Labels: 📄 Documentation 📄

#201 ci: fix ruby setup for deployment scripts in Github Actions
  .github/workflows/deploy-firebase-android.yml
  .github/workflows/deploy-firebase-ios.yml
  starport_template/ios/fastlane/Fastfile
Labels: Technical 🛠
