Repository tendermint/flutter, pull requests merged in 2022-04, with the labels that each got.

#247 fix: Add factory constructor in app_info_extractor.dart
  packages/cosmos_utils/lib/app_info_extractor.dart
Labels: bug 🐛

#248 feat: AppInfo improvements
  packages/cosmos_utils/lib/app_info_extractor.dart
Labels: Feature 💡

#249 fix: make account info reading backward-compatibile
  packages/transaction_signing_gateway/lib/model/account_public_info_serializer.dart
Labels: bug 🐛

#250 refactor: Migrate from `mockito` to `mocktail` in `TransactionSigningGateway`
  packages/transaction_signing_gateway/pubspec.lock
  packages/transaction_signing_gateway/pubspec.yaml
  packages/transaction_signing_gateway/test/mocks/key_info_storage_mock.dart
  packages/transaction_signing_gateway/test/mocks/transaction_summary_ui_mock.dart
  packages/transaction_signing_gateway/test/transaction_signing_gateway_test.dart
Labels: Technical 🛠, 🛠 Refactor 🛠

#251 refactor: Extract `AppVersionText` into a separate widget + Add a new widget = `ChipText`
  packages/cosmos_ui_components/lib/components/app_version_text.dart
  packages/cosmos_ui_components/lib/components/chip_text.dart
  packages/cosmos_ui_components/lib/cosmos_ui_components.dart
Labels: 🛠 Refactor 🛠

#244 feat: created config base env file
  Makefile
  packages/cosmos_auth/pubspec.lock
  packages/cosmos_auth/test/mocks/mocks.dart
  packages/cosmos_ui_components/pubspec.lock
  packages/transaction_signing_gateway/pubspec.lock
  starport_template/README.md
  starport_template/lib/app_config.dart
  starport_template/lib/main.dart
  starport_template/lib/starport_app.dart
  starport_template/lib/stores/accounts_store.dart
  starport_template/lib/stores/settings_store.dart
  starport_template/lib/stores/transactions_store.dart
  starport_template/lib/utils/base_env.dart
  starport_template/lib/utils/cosmos_balances.dart
  starport_template/lib/utils/cosmos_transaction_history_loader.dart
  starport_template/lib/utils/node_info_loader.dart
  starport_template/pubspec.lock
Labels: 🔴 DO NOT MERGE 🔴

#253 refactor: Add optional color property to `CosmosBackButton`
  packages/cosmos_ui_components/lib/components/cosmos_back_button.dart
Labels: 🛠 Refactor 🛠, 🎨 Design 🎨

#261 feat: create cosmos_lint package
  .github/workflows/pull-request.yml
  Makefile
  packages/cosmos_lint/CHANGELOG.md
  packages/cosmos_lint/LICENSE
  packages/cosmos_lint/README.md
  packages/cosmos_lint/analysis_options.yaml
  packages/cosmos_lint/lib/analysis_options.yaml
  packages/cosmos_lint/lib/lint.dart
  packages/cosmos_lint/pubspec.lock
  packages/cosmos_lint/pubspec.yaml
Labels: Technical 🛠
